pipeline {
    agent any

    stages {


        stage('Backend Lint & Build') {
            steps {
                echo 'Linting Java code with Checkstyle...'
                sh 'mvn checkstyle:check'
                echo 'Building backend...'
                sh 'mvn clean install'
            }
        }

        stage('Docker Lint & Build') {
            steps {
                echo 'Linting Dockerfile...'
                sh 'docker run --rm -i hadolint/hadolint < Dockerfile'
                echo 'Building Docker image...'
                sh 'docker build -t spring-boot-app .'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
